In [2]:
import pandas as pd

In [3]:
youth = pd.read_excel('../EA_Data/youth.xlsx')
compare = pd.read_excel('../results/ecm_result4.4.xlsx')

In [6]:
youth.set_index(['시군구','year'],inplace=True)
compare.set_index(['시군구','year'],inplace=True)

In [13]:
youth.index.nunique() == youth.index.shape[0]

False

In [17]:
youth[youth.index.duplicated()]

            Unnamed: 0     시도 통합 필드    hos    cf    kin  elementary  doctors  \
시군구   year
광주광역시 2018         720  광주광역시    광주  57.70  4.32  24609       88622   3547.0
      2017         899  광주광역시    광주  57.02  4.17  24654       88189   3497.0
      2016        1078  광주광역시    광주  56.98  3.90  24790       89095   3434.0
      2015        1257  광주광역시    광주    NaN  3.80  23741       91862   3292.0
      2014        1436  광주광역시    광주    NaN  3.66  22288       93163   3194.0
      2013        1615  광주광역시    광주    NaN  3.39  22676       96055   3112.0
      2012        1794  광주광역시    광주    NaN  3.13  20445      102912   3023.0
      2011        1973  광주광역시    광주    NaN  2.87  18549      109760   2991.0
      2010        2152  광주광역시    광주    NaN  2.80  17165      115827   2861.0
      2009        2331  광주광역시    광주    NaN  2.93  17193      121590   2664.0
      2008        2510  광주광역시    광주    NaN  2.60  17091      127758   2669.0

            qlifea  qlifes  ...        grdp  unsold  apt_trans  ktx  \
시군구   year                  ...
광주광역시 2018    0.96    0.97  ...  39805406.0      58    50792.0    1
      2017    0.95    0.96  ...  37743917.0     707    48666.0    1
      2016    0.95    0.96  ...  36819006.0     554    36137.0    1
      2015    0.95    0.96  ...  34845589.0     735    46912.0    1
      2014    0.95    0.95  ...  33016736.0     247    52865.0    1
      2013    0.95    0.96  ...  31263021.0     323    42039.0    1
      2012    0.96    0.96  ...  29773635.0    3348    33483.0    1
      2011    0.95    0.96  ...  28678421.0     784    42936.0    1
      2010    0.96    0.96  ...  27882311.0    1809    35793.0    1
      2009    0.96    0.96  ...  22066126.0    4678    43889.0    1
      2008    0.95    0.95  ...  21745349.0   12384    34456.0    1

            seoul_dist     ep    er   ur   s  youth
시군구   year
광주광역시 2018       268.0  779.0  59.4  3.8 NaN  0.199
      2017       268.0  766.0  59.0  2.9 NaN  0.201
      2016       268.0  753.0  58.1  3.1 NaN  0.204
      2015       268.0  755.0  58.5  2.9 NaN  0.207
      2014       268.0  753.0  58.8  2.8 NaN  0.210
      2013       268.0  727.0  57.2  2.8 NaN  0.213
      2012       268.0  710.0  56.4  2.7 NaN  0.214
      2011       268.0  709.0  56.6  3.1 NaN  0.217
      2010       268.0  705.0  56.9  3.5 NaN  0.235
      2009       268.0  688.0  56.4  3.8 NaN  0.239
      2008       268.0  676.0  56.4  3.8 NaN  0.245

[11 rows x 39 columns]

In [14]:
compare.index.nunique() == compare.index.shape[0]

True

In [7]:
diff = youth.index.symmetric_difference(compare.index)

In [8]:
diff

MultiIndex([], names=['시군구', 'year'])